textPlay = "press any button to play"; 

credits = "Coding By Brent VanZant";
creditsTwo = "Art by Orlando Herrara and RVROS";
isActive = false 
titleText = "Versus"
xTitle = room_width/2;
yTitle = (room_height/2)-(room_height/4);
blueOffsetCurr = 4;
redOffsetMax = 10;
redOffsetCurr = 4;
redOffsetMin = 2; 
offsetX = 2;
redIsUp = true;
myAlpha = 0.7;
alphaUp = true;
isMoving = false; 
xTitle = room_width/2;
yTitle = (room_height/2)-(room_height/4);
xPlay = room_width/2;
yPlay = room_height/2;
yCredits = room_height - room_height/8;
yCreditsTwo = room_height - room_height/16;
alarm[2] = 1 
redColor = make_color_rgb(219,38,37);
blueColor = make_color_rgb(37,146,178);